# Generated by Django 5.2.8 on 2025-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heroname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='heronames/')),
                ('age', models.IntegerField()),
                ('herotype', models.CharField(choices=[('warrior', 'Warrior'), ('mage', 'Mage'), ('archer', 'Archer'), ('healer', 'Healer')], default='warrior', max_length=20)),
            ],
        ),
    ]
