# Generated by Django 5.2.8 on 2025-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroname',
            name='abilities',
            field=models.TextField(default='No abilities listed.'),
        ),
        migrations.AlterField(
            model_name='heroname',
            name='herotype',
            field=models.CharField(choices=[('warrior', 'Warrior'), ('mage', 'Mage'), ('archer', 'Archer'), ('healer', 'Healer')], max_length=20),
        ),
    ]
