# Generated by Django 5.2.8 on 2025-12-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farty', '0002_heroname_abilities_alter_heroname_herotype'),
    ]

    operations = [
        migrations.CreateModel(
            name='association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(to='farty.heroname')),
            ],
        ),
        migrations.CreateModel(
            name='hero_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farty.heroname')),
            ],
        ),
    ]
